# Generated by Django 4.0.1 on 2024-05-09 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapatransaction',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chapatransaction',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='chapatransaction',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='chapatransaction',
            name='patients_id',
        ),
        migrations.RemoveField(
            model_name='chapatransaction',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='chapatransaction',
            name='therapists_id',
        ),
        migrations.AddField(
            model_name='chapatransaction',
            name='therapist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='therapistPayment', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapatransaction',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientPayment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChapaTransactions',
        ),
    ]
