# Generated by Django 4.0.1 on 2024-05-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='content',
            new_name='patientContent',
        ),
        migrations.AddField(
            model_name='notification',
            name='therapistContent',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
