# Generated by Django 5.0.4 on 2024-05-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='paymentRate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='therapist',
            name='totalBalance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='therapist',
            name='withdrawableBalance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prefered_language',
            field=models.CharField(choices=[('AMHARIC', 'Amharic'), ('OROMIFA', 'Oromifa'), ('SOMALLI', 'Somalli'), ('TIGRIGNA', 'Tigrigna'), ('ENGLISH', 'English')], default='English', max_length=10),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='religion',
            field=models.CharField(choices=[('ORTHODOX', 'Orthodox'), ('CHATHOLIC', 'Catholic'), ('PROTESTANT', 'Protestant'), ('MUSLIM', 'Muslim')], max_length=10),
        ),
    ]
